apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/Arvelog/kbot.git
      type: git
      name: kbot-repo
      gpg: false  # Disable GnuPG key generation