replicaCount: 1
# v1.2.0-660ae95
image:
  registry: "ghcr.io"
  repository: "arvelog/kbot"
  pullPolicy: IfNotPresent
  tag: "v0.0.1-9-ga5c6534" # Set a default value, will be updated dynamically in the workflow
  os: linux
  arch: amd64
  parameter: go
# Remove the hardcoded TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
# Remove the invalid privileged field
