replicaCount: 1
# v1.2.0-660ae95
image:
  registry: "ghcr.io"
  repository: "arvelog/kbot"
  pullPolicy: IfNotPresent # Дозволяє замінити образ за замовчуванням
  tag: v1.5.0-8791e23
  os: linux
  arch: amd64
  parameter: go
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
  value: "7090648610:AAEKZl6thxmngf5pzGDWSZek1GHFhN9TiLE"
securityContext:
  privileged: true
