# File: .github/workflows/cicd.yaml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: DNS Lookup for Kubernetes API Server
      run: nslookup 127.0.0.1

    - name: Check Connectivity to Kubernetes API Server
      run: |
        curl -vk http://127.0.0.1:6443 || echo "Unable to reach the Kubernetes API Server"
        ping -c 4 127.0.0.1 || echo "Ping failed for the Kubernetes API Server"

    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yaml --server=http://127.0.0.1:6443
